export const CLIENT_CODE_SUCCESS = "CLIENT_CODE_SUCCESS";
export const CLIENT_CODE_ERROR = "CLIENT_CODE_ERROR";
export const CLIENT_CODE_LOADING = "CLIENT_CODE_LOADING";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_ERROR = "AUTHENTICATED_ERROR";
export const AUTHENTICATED_LOADING = "AUTHENTICATED_LOADING";

export const BPOS_USER_SERVICE_SUCCESS = "BPOS_USER_SERVICE_SUCCESS";
export const BPOS_USER_SERVICE_ERROR = "BPOS_USER_SERVICE_ERROR";
export const BPOS_USER_SERVICE_LOADING = "BPOS_USER_SERVICE_LOADING";

export const GET_CLIENT_INFO_SUCCESS = "GET_CLIENT_INFO_SUCCESS";
export const GET_CLIENT_INFO_ERROR = "GET_CLIENT_INFO_ERROR";
export const GET_CLIENT_INFO_LOADING = "GET_CLIENT_INFO_LOADING";

export const GET_PARTNER_TOKEN_DETAILS_SUCCESS = "GET_PARTNER_TOKEN_DETAILS_SUCCESS";
export const GET_PARTNER_TOKEN_DETAILS_ERROR = "GET_PARTNER_TOKEN_DETAILS_ERROR";
export const GET_PARTNER_TOKEN_DETAILS_LOADING = "GET_PARTNER_TOKEN_DETAILS_LOADING";

export const GET_IMD_WISE_GROUP_PRODUCT_CODE_SUCCESS = "GET_IMD_WISE_GROUP_PRODUCT_CODE_SUCCESS";
export const GET_IMD_WISE_GROUP_PRODUCT_CODE_ERROR = "GET_IMD_WISE_GROUP_PRODUCT_CODE_ERROR";
export const GET_IMD_WISE_GROUP_PRODUCT_CODE_LOADING = "GET_IMD_WISE_GROUP_PRODUCT_CODE_LOADING";

export const GENERATE_OTP_SUCCESS = "GENERATE_OTP_SUCCESS";
export const GENERATE_OTP_ERROR = "GENERATE_OTP_ERROR";
export const GENERATE_OTP_LOADING = "GENERATE_OTP_LOADING";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";
export const VERIFY_OTP_LOADING = "VERIFY_OTP_LOADING";

export const SAVE_DATA_SUCCESS = "SAVE_DATA_SUCCESS";
export const SAVE_DATA_ERROR = "SAVE_DATA_ERROR";
export const SAVE_DATA_LOADING = "SAVE_DATA_LOADING";

export const STORE_JOURNEY_DATA_SUCCESS = "STORE_JOURNEY_DATA_SUCCESS";
export const STORE_JOURNEY_DATA_ERROR = "STORE_JOURNEY_DATA_ERROR";
export const STORE_JOURNEY_DATA_LOADING = "STORE_JOURNEY_DATA_LOADING";

export const SAVE_DATA_FOR_NOMINEE_SUCCESS = "SAVE_DATA_FOR_NOMINEE_SUCCESS";
export const SAVE_DATA_FOR_NOMINEE_ERROR = "SAVE_DATA_FOR_NOMINEE_ERROR";
export const SAVE_DATA_FOR_NOMINEE_LOADING = "SAVE_DATA_FOR_NOMINEE_LOADING";

export const SAVE_PREMIUM_DATA_SUCCESS = "SAVE_PREMIUM_DATA_SUCCESS";
export const SAVE_PREMIUM_DATA_ERROR = "SAVE_PREMIUM_DATA_ERROR";
export const SAVE_PREMIUM_DATA_LOADING = "SAVE_PREMIUM_DATA_LOADING";